/**
 * Screen 7: Generate 7 Days of Multi-Channel Content
 * 
 * Automatically generates:
 * - 5 social posts
 * - 1 email
 * - 1 Google Business Profile post
 * - 1 blog/caption expansion (optional)
 * 
 * Shows magical loading sequence.
 */

import { useState, useEffect } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { Sparkles, CheckCircle2, Loader2, Instagram, Mail, MapPin, FileText } from "lucide-react";
import { OnboardingProgress } from "@/components/onboarding/OnboardingProgress";
import { useConfetti } from "@/hooks/useConfetti";
import { logError } from "@/lib/logger";

interface GenerationStep {
  id: string;
  label: string;
  platform: string;
  status: "pending" | "processing" | "complete";
  icon: typeof Instagram;
}

const GENERATION_STEPS: GenerationStep[] = [
  {
    id: "social-1",
    label: "Creating an engaging Instagram post with hashtags and CTA",
    platform: "Instagram",
    status: "pending",
    icon: Instagram,
  },
  {
    id: "social-2",
    label: "Crafting a professional LinkedIn post for your audience",
    platform: "LinkedIn",
    status: "pending",
    icon: Instagram,
  },
  {
    id: "social-3",
    label: "Creating a Facebook post optimized for engagement",
    platform: "Facebook",
    status: "pending",
    icon: Instagram,
  },
  {
    id: "social-4",
    label: "Crafting a concise, impactful Twitter post",
    platform: "Twitter",
    status: "pending",
    icon: Instagram,
  },
  {
    id: "social-5",
    label: "Writing another Instagram post with different angle",
    platform: "Instagram",
    status: "pending",
    icon: Instagram,
  },
  {
    id: "email",
    label: "Creating an email with subject line and body content",
    platform: "Email",
    status: "pending",
    icon: Mail,
  },
  {
    id: "gbp",
    label: "Creating a local-optimized Google Business Profile post",
    platform: "Google Business",
    status: "pending",
    icon: MapPin,
  },
  {
    id: "blog",
    label: "Writing a 500+ word blog post ready to publish",
    platform: "Blog",
    status: "pending",
    icon: FileText,
  },
];

export default function Screen7ContentGeneration() {
  const { user, brandSnapshot, setOnboardingStep } = useAuth();
  const { fire } = useConfetti();
  const [steps, setSteps] = useState<GenerationStep[]>(GENERATION_STEPS);
  const [isComplete, setIsComplete] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    startGeneration();
  }, []);

  const startGeneration = async () => {
    try {
      // Get brandId from context or localStorage
      const brandId = localStorage.getItem("aligned_brand_id") || (brandSnapshot as any)?.brandId;
      
      if (!brandId) {
        setError("Brand ID not found. Please restart onboarding.");
        return;
      }

      // Call the content planning API to generate content
      let contentPlanData: any = null;
      try {
        // ✅ FIX: Use authenticated API utility (includes Authorization header)
        const { apiPost } = await import("@/lib/api");
        const data = await apiPost(`/api/content-plan/${brandId}/generate`, {});
        
        if (data.success && data.contentPlan) {
          contentPlanData = data.contentPlan;
          // Store content plan for Screen8CalendarPreview
          localStorage.setItem("aligned:onboarding:content_package", JSON.stringify({
            items: data.contentPlan.items,
            generatedAt: data.contentPlan.generatedAt,
          }));
        }
      } catch (apiError) {
        // ✅ ENHANCED ERROR HANDLING: Log full error and show user-friendly message
        const errorMessage = apiError instanceof Error ? apiError.message : String(apiError);
        logError("Content planning API error", apiError instanceof Error ? apiError : new Error(errorMessage), {
          step: "content_generation",
        });
        
        // Set error state so user knows generation failed
        setError(`Content generation failed: ${errorMessage}. Please try again or contact support.`);
        // Continue with UI simulation even if API fails (don't block onboarding)
      }

      // Simulate progress through each step to show UI feedback
      // Map actual generated items to UI steps if available
      const generatedItems = contentPlanData?.items || [];
      const stepMapping: Record<string, number> = {
        "social-1": 0,
        "social-2": 1,
        "social-3": 2,
        "social-4": 3,
        "social-5": 4,
        "email": generatedItems.findIndex((item: any) => item.contentType === "email"),
        "gbp": -1, // Not generated by content planning service
        "blog": generatedItems.findIndex((item: any) => item.contentType === "blog"),
      };

      for (let i = 0; i < steps.length; i++) {
        const step = steps[i];
        setSteps((prev) =>
          prev.map((s, idx) =>
            idx === i
              ? { ...s, status: "processing" }
              : idx < i
              ? { ...s, status: "complete" }
              : s
          )
        );

        // Check if this step has corresponding generated content
        const itemIndex = stepMapping[step.id];
        if (itemIndex >= 0 && itemIndex < generatedItems.length) {
          // Real content was generated for this step
          await new Promise((resolve) => setTimeout(resolve, 800));
        } else if (step.id === "gbp") {
          // Google Business Post is not generated, skip quickly
          await new Promise((resolve) => setTimeout(resolve, 300));
        } else {
          // Simulate processing time for other steps
          await new Promise((resolve) => setTimeout(resolve, 1200 + Math.random() * 800));
        }

        // Mark step as complete
        setSteps((prev) =>
          prev.map((s, idx) =>
            idx === i ? { ...s, status: "complete" } : s
          )
        );
      }

      // Celebrate completion
      setIsComplete(true);
      fire({
        particleCount: 150,
        spread: 80,
        origin: { y: 0.5 },
        colors: ["#632bf0", "#c084fc", "#e2e8f0", "#a855f7", "#12b76a"], // primary-light, purple-400, slate-200, purple-500, success (design tokens)
      });

      // Move to calendar preview after a moment
      setTimeout(() => {
        setOnboardingStep(8);
      }, 2500);
    } catch (err) {
      logError("Content generation error", err instanceof Error ? err : new Error(String(err)), {
        step: "content_generation",
      });
      setError(err instanceof Error ? err.message : "Failed to generate content");
      // Still mark steps as complete to allow progression
      setSteps((prev) => prev.map((s) => ({ ...s, status: "complete" })));
      setIsComplete(true);
      // Still proceed to calendar preview
      setTimeout(() => {
        setOnboardingStep(8);
      }, 2000);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-indigo-50/30 via-white to-blue-50/20 flex items-center justify-center p-4">
      <div className="w-full max-w-3xl">
        {/* Progress Indicator */}
        <OnboardingProgress currentStep={7} totalSteps={10} label="Generating your week" />

        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-br from-indigo-600 to-purple-600 mb-4 animate-pulse">
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-4xl font-black text-slate-900 mb-3">
            Creating your first week of content
          </h1>
          <p className="text-slate-600 font-medium text-lg mb-2">
            Our AI is writing personalized content for each platform.<br />
            This usually takes 2-3 minutes.
          </p>
        </div>

        {/* Generation Steps */}
        <div className="bg-white/50 backdrop-blur-xl rounded-2xl border border-white/60 p-8 space-y-4">
          {steps.map((step, index) => {
            const Icon = step.icon;
            return (
              <div
                key={step.id}
                className={`flex items-center gap-4 p-4 rounded-lg transition-all ${
                  step.status === "complete"
                    ? "bg-green-50 border border-green-200"
                    : step.status === "processing"
                    ? "bg-indigo-50 border border-indigo-200"
                    : "bg-slate-50 border border-slate-200"
                }`}
              >
                {/* Icon */}
                <div
                  className={`flex-shrink-0 ${
                    step.status === "complete"
                      ? "text-green-600"
                      : step.status === "processing"
                      ? "text-indigo-600"
                      : "text-slate-400"
                  }`}
                >
                  {step.status === "complete" ? (
                    <CheckCircle2 className="w-6 h-6" />
                  ) : step.status === "processing" ? (
                    <Loader2 className="w-6 h-6 animate-spin" />
                  ) : (
                    <Icon className="w-6 h-6" />
                  )}
                </div>

                {/* Content */}
                <div className="flex-1">
                  <p
                    className={`font-bold text-sm ${
                      step.status === "complete"
                        ? "text-green-900"
                        : step.status === "processing"
                        ? "text-indigo-900"
                        : "text-slate-600"
                    }`}
                  >
                    {step.label}
                  </p>
                  <p className="text-xs text-slate-500 mt-0.5">{step.platform}</p>
                  {step.status === "processing" && (
                    <div className="mt-2 h-1 bg-indigo-200 rounded-full overflow-hidden">
                      <div className="h-full bg-indigo-600 rounded-full animate-pulse" style={{ width: "60%" }} />
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>

        {/* Error Message */}
        {error && (
          <div className="mt-6 p-4 bg-amber-50 border border-amber-200 rounded-lg">
            <p className="text-sm font-semibold text-amber-900 mb-1">
              ⚠️ Content generation is taking longer than expected
            </p>
            <p className="text-xs text-amber-800">
              {error}. Don't worry—we'll create a default content plan you can customize.
            </p>
          </div>
        )}

        {/* Completion Message */}
        {isComplete && (
          <div className="mt-6 p-4 bg-green-50 border border-green-200 rounded-lg text-center">
            <p className="text-lg font-bold text-green-900 mb-1">
              🎉 Your first week of content is ready!
            </p>
            <p className="text-sm text-green-700">
              8 pieces of content, ready to review and publish. Taking you to calendar...
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

