-- Content Planning Schema Clarification
-- Migration: 008
-- Date: 2025-01-20
-- Purpose: Document canonical content planning tables and mark archived migration as obsolete

-- ============================================================================
-- CONTENT PLANNING TABLES - CANONICAL SCHEMA
-- ============================================================================
--
-- The following tables are the canonical schema for content planning:
--
-- 1. auto_plans (UUID brand_id)
--    - Stores monthly content plans generated by Advisor Agent
--    - Used by: server/lib/auto-plan-generator.ts, server/lib/analytics-scheduler.ts
--    - Structure: brand_id (UUID), month (DATE), plan_data (JSONB), confidence (NUMERIC)
--
-- 2. scheduled_content (UUID brand_id)
--    - Links content_items to scheduled publishing times
--    - Used by: server/routes/agents.ts, server/lib/approvals-db-service.ts
--    - Structure: brand_id (UUID), content_id (UUID FK), scheduled_at (TIMESTAMPTZ), platforms (TEXT[])
--
-- 3. content_items (UUID brand_id)
--    - Primary content storage (posts, captions, scripts, etc.)
--    - Links to: scheduled_content, post_approvals
--    - Structure: brand_id (UUID), type, content (JSONB), platform, status
--
-- ============================================================================
-- ARCHIVED MIGRATION STATUS
-- ============================================================================
--
-- supabase/migrations/archived/20250118_create_content_calendar_tables.sql
-- Status: OBSOLETE - Do not apply
--
-- This archived migration defined:
-- - monthly_content_plans (different structure than auto_plans)
-- - scheduled_content (different structure than canonical)
-- - performance_metrics, performance_adjustments
--
-- The current codebase uses:
-- - auto_plans (not monthly_content_plans)
-- - scheduled_content (canonical structure in bootstrap schema)
-- - analytics_metrics (exists in bootstrap schema, different from archived)
--
-- The archived migration was a planning document and is superseded by the
-- bootstrap schema (001_bootstrap_schema.sql) and subsequent migrations.
--
-- ============================================================================
-- NO SCHEMA CHANGES
-- ============================================================================
--
-- This migration is documentation-only. No tables are created or modified.
-- The canonical schema is already defined in 001_bootstrap_schema.sql.

COMMENT ON TABLE auto_plans IS 'Canonical table for monthly content plans generated by Advisor Agent. Replaces archived monthly_content_plans table.';
COMMENT ON TABLE scheduled_content IS 'Canonical table for linking content_items to scheduled publishing times. Structure differs from archived migration.';
COMMENT ON TABLE content_items IS 'Primary content storage table. All generated content (posts, captions, scripts) is stored here.';

