import { Design, DesignFormat } from "@/types/creativeStudio";

export interface DesignTemplate {
  id: string;
  name: string;
  category: "social" | "email" | "blog" | "general";
  description: string;
  format: DesignFormat;
  preview: string;
  design: Omit<Design, "id" | "brandId" | "campaignId" | "createdAt" | "updatedAt">;
}

export const DESIGN_TEMPLATES: DesignTemplate[] = [
  {
    id: "template-hero-social",
    name: "Hero + Text",
    category: "social",
    description: "Bold headline with background image - perfect for announcements",
    format: "social_square",
    preview: "🎨 Large image with overlaid text",
    design: {
      name: "Hero Social Post",
      format: "social_square",
      width: 1080,
      height: 1080,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          rotation: 0,
          zIndex: 0,
          backgroundType: "solid",
          backgroundColor: "#1F2937",
        },
        {
          id: "image-1",
          type: "image",
          x: 0,
          y: 0,
          width: 1080,
          height: 600,
          rotation: 0,
          zIndex: 1,
          imageUrl: "placeholder",
          imageName: "hero-image",
        },
        {
          id: "overlay-1",
          type: "shape",
          x: 0,
          y: 600,
          width: 1080,
          height: 480,
          rotation: 0,
          zIndex: 2,
          shapeType: "rectangle",
          fill: "#000000",
        },
        {
          id: "text-1",
          type: "text",
          x: 54,
          y: 700,
          width: 972,
          height: 200,
          rotation: 0,
          zIndex: 3,
          text: "Your Headline Here",
          fontSize: 48,
          fontFamily: "Arial",
          fontColor: "#FFFFFF",
          fontWeight: "900",
          textAlign: "center",
        },
        {
          id: "text-2",
          type: "text",
          x: 54,
          y: 900,
          width: 972,
          height: 100,
          rotation: 0,
          zIndex: 3,
          text: "Supporting text or description",
          fontSize: 24,
          fontFamily: "Arial",
          fontColor: "#E5E7EB",
          fontWeight: "normal",
          textAlign: "center",
        },
      ],
      backgroundColor: "#1F2937",
      savedToLibrary: false,
    },
  },

  {
    id: "template-three-column",
    name: "Three Column Layout",
    category: "social",
    description: "Three distinct sections for showcasing features or benefits",
    format: "social_square",
    preview: "📊 Three equal columns",
    design: {
      name: "Three Column Post",
      format: "social_square",
      width: 1080,
      height: 1080,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          rotation: 0,
          zIndex: 0,
          backgroundType: "solid",
          backgroundColor: "#FFFFFF",
        },
        {
          id: "header",
          type: "text",
          x: 54,
          y: 54,
          width: 972,
          height: 100,
          rotation: 0,
          zIndex: 1,
          text: "Section Title",
          fontSize: 48,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "900",
          textAlign: "center",
        },
        {
          id: "col1-bg",
          type: "shape",
          x: 54,
          y: 200,
          width: 300,
          height: 700,
          rotation: 0,
          zIndex: 1,
          shapeType: "rectangle",
          fill: "#EEF2FF",
        },
        {
          id: "col2-bg",
          type: "shape",
          x: 390,
          y: 200,
          width: 300,
          height: 700,
          rotation: 0,
          zIndex: 1,
          shapeType: "rectangle",
          fill: "#F3F4F6",
        },
        {
          id: "col3-bg",
          type: "shape",
          x: 726,
          y: 200,
          width: 300,
          height: 700,
          rotation: 0,
          zIndex: 1,
          shapeType: "rectangle",
          fill: "#F9FAFB",
        },
        {
          id: "col1-text",
          type: "text",
          x: 80,
          y: 450,
          width: 250,
          height: 150,
          rotation: 0,
          zIndex: 2,
          text: "Feature One",
          fontSize: 28,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "bold",
          textAlign: "center",
        },
        {
          id: "col2-text",
          type: "text",
          x: 416,
          y: 450,
          width: 250,
          height: 150,
          rotation: 0,
          zIndex: 2,
          text: "Feature Two",
          fontSize: 28,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "bold",
          textAlign: "center",
        },
        {
          id: "col3-text",
          type: "text",
          x: 752,
          y: 450,
          width: 250,
          height: 150,
          rotation: 0,
          zIndex: 2,
          text: "Feature Three",
          fontSize: 28,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "bold",
          textAlign: "center",
        },
      ],
      backgroundColor: "#FFFFFF",
      savedToLibrary: false,
    },
  },

  {
    id: "template-quote",
    name: "Quote Post",
    category: "social",
    description: "Minimalist quote design with brand colors",
    format: "social_square",
    preview: "💬 Centered quote with accent",
    design: {
      name: "Inspirational Quote",
      format: "social_square",
      width: 1080,
      height: 1080,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          rotation: 0,
          zIndex: 0,
          backgroundType: "gradient",
          gradientFrom: "#6366F1",
          gradientTo: "#8B5CF6",
          gradientAngle: 135,
        },
        {
          id: "accent-line",
          type: "shape",
          x: 450,
          y: 300,
          width: 180,
          height: 8,
          rotation: 0,
          zIndex: 1,
          shapeType: "rectangle",
          fill: "#FBBF24",
        },
        {
          id: "quote-text",
          type: "text",
          x: 108,
          y: 400,
          width: 864,
          height: 300,
          rotation: 0,
          zIndex: 2,
          text: '"Your inspirational quote goes here"',
          fontSize: 56,
          fontFamily: "Arial",
          fontColor: "#FFFFFF",
          fontWeight: "bold",
          textAlign: "center",
        },
        {
          id: "author-text",
          type: "text",
          x: 108,
          y: 750,
          width: 864,
          height: 100,
          rotation: 0,
          zIndex: 2,
          text: "— Your Name",
          fontSize: 28,
          fontFamily: "Arial",
          fontColor: "#F3F4F6",
          fontWeight: "normal",
          textAlign: "center",
        },
      ],
      backgroundColor: "#6366F1",
      savedToLibrary: false,
    },
  },

  {
    id: "template-product-showcase",
    name: "Product Showcase",
    category: "social",
    description: "Left image, right text layout for product promotion",
    format: "social_square",
    preview: "📦 Product focus layout",
    design: {
      name: "Product Post",
      format: "social_square",
      width: 1080,
      height: 1080,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          rotation: 0,
          zIndex: 0,
          backgroundType: "solid",
          backgroundColor: "#F8FAFC",
        },
        {
          id: "image-1",
          type: "image",
          x: 54,
          y: 150,
          width: 450,
          height: 780,
          rotation: 0,
          zIndex: 1,
          imageUrl: "placeholder",
          imageName: "product-image",
        },
        {
          id: "text-bg",
          type: "shape",
          x: 540,
          y: 150,
          width: 486,
          height: 780,
          rotation: 0,
          zIndex: 1,
          shapeType: "rectangle",
          fill: "#FFFFFF",
        },
        {
          id: "text-title",
          type: "text",
          x: 594,
          y: 250,
          width: 378,
          height: 150,
          rotation: 0,
          zIndex: 2,
          text: "Product Name",
          fontSize: 40,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "900",
          textAlign: "left",
        },
        {
          id: "text-desc",
          type: "text",
          x: 594,
          y: 450,
          width: 378,
          height: 200,
          rotation: 0,
          zIndex: 2,
          text: "Describe your amazing product and why customers love it.",
          fontSize: 20,
          fontFamily: "Arial",
          fontColor: "#4B5563",
          fontWeight: "normal",
          textAlign: "left",
        },
        {
          id: "cta-text",
          type: "text",
          x: 594,
          y: 750,
          width: 378,
          height: 80,
          rotation: 0,
          zIndex: 2,
          text: "Shop Now →",
          fontSize: 28,
          fontFamily: "Arial",
          fontColor: "#3B82F6",
          fontWeight: "bold",
          textAlign: "left",
        },
      ],
      backgroundColor: "#F8FAFC",
      savedToLibrary: false,
    },
  },

  {
    id: "template-testimonial",
    name: "Customer Testimonial",
    category: "social",
    description: "Social proof with customer quote and image",
    format: "social_square",
    preview: "⭐ Review/testimonial layout",
    design: {
      name: "Testimonial Post",
      format: "social_square",
      width: 1080,
      height: 1080,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          rotation: 0,
          zIndex: 0,
          backgroundType: "solid",
          backgroundColor: "#FFFFFF",
        },
        {
          id: "stars",
          type: "text",
          x: 54,
          y: 150,
          width: 972,
          height: 80,
          rotation: 0,
          zIndex: 1,
          text: "★★★★★",
          fontSize: 56,
          fontFamily: "Arial",
          fontColor: "#FBBF24",
          fontWeight: "bold",
          textAlign: "center",
        },
        {
          id: "quote-text",
          type: "text",
          x: 108,
          y: 300,
          width: 864,
          height: 250,
          rotation: 0,
          zIndex: 1,
          text: '"This product changed my life! Highly recommend to everyone."',
          fontSize: 32,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "bold",
          textAlign: "center",
        },
        {
          id: "author-avatar",
          type: "shape",
          x: 450,
          y: 650,
          width: 180,
          height: 180,
          rotation: 0,
          zIndex: 1,
          shapeType: "circle",
          fill: "#E5E7EB",
        },
        {
          id: "author-name",
          type: "text",
          x: 108,
          y: 900,
          width: 864,
          height: 60,
          rotation: 0,
          zIndex: 1,
          text: "Sarah Johnson, Happy Customer",
          fontSize: 24,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "bold",
          textAlign: "center",
        },
      ],
      backgroundColor: "#FFFFFF",
      savedToLibrary: false,
    },
  },

  {
    id: "template-story-vertical",
    name: "Story/Vertical Video",
    category: "social",
    description: "Full-height vertical design for Stories and Reels",
    format: "story_portrait",
    preview: "📱 Vertical story format",
    design: {
      name: "Story Post",
      format: "story_portrait",
      width: 1080,
      height: 1920,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1080,
          height: 1920,
          rotation: 0,
          zIndex: 0,
          backgroundType: "gradient",
          gradientFrom: "#EC4899",
          gradientTo: "#8B5CF6",
          gradientAngle: 45,
        },
        {
          id: "text-main",
          type: "text",
          x: 54,
          y: 800,
          width: 972,
          height: 300,
          rotation: 0,
          zIndex: 1,
          text: "Your Story Headline",
          fontSize: 64,
          fontFamily: "Arial",
          fontColor: "#FFFFFF",
          fontWeight: "900",
          textAlign: "center",
        },
        {
          id: "cta-button",
          type: "shape",
          x: 300,
          y: 1400,
          width: 480,
          height: 120,
          rotation: 0,
          zIndex: 1,
          shapeType: "rectangle",
          fill: "#FFFFFF",
        },
        {
          id: "cta-text",
          type: "text",
          x: 300,
          y: 1400,
          width: 480,
          height: 120,
          rotation: 0,
          zIndex: 2,
          text: "Tap to Learn More",
          fontSize: 32,
          fontFamily: "Arial",
          fontColor: "#EC4899",
          fontWeight: "bold",
          textAlign: "center",
        },
      ],
      backgroundColor: "#EC4899",
      savedToLibrary: false,
    },
  },

  {
    id: "template-blog-hero",
    name: "Blog Header Image",
    category: "blog",
    description: "Wide header image for blog posts",
    format: "blog_featured",
    preview: "📰 Blog header layout",
    design: {
      name: "Blog Featured Image",
      format: "blog_featured",
      width: 1200,
      height: 675,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1200,
          height: 675,
          rotation: 0,
          zIndex: 0,
          backgroundType: "solid",
          backgroundColor: "#1F2937",
        },
        {
          id: "image-1",
          type: "image",
          x: 0,
          y: 0,
          width: 1200,
          height: 675,
          rotation: 0,
          zIndex: 1,
          imageUrl: "placeholder",
          imageName: "blog-hero",
        },
        {
          id: "overlay",
          type: "shape",
          x: 0,
          y: 0,
          width: 1200,
          height: 675,
          rotation: 0,
          zIndex: 2,
          shapeType: "rectangle",
          fill: "#000000",
          stroke: "none",
        },
        {
          id: "title",
          type: "text",
          x: 60,
          y: 200,
          width: 1080,
          height: 300,
          rotation: 0,
          zIndex: 3,
          text: "Your Blog Post Title Goes Here",
          fontSize: 52,
          fontFamily: "Arial",
          fontColor: "#FFFFFF",
          fontWeight: "900",
          textAlign: "left",
        },
      ],
      backgroundColor: "#1F2937",
      savedToLibrary: false,
    },
  },

  {
    id: "template-email-header",
    name: "Email Banner",
    category: "email",
    description: "Eye-catching email header with CTA button",
    format: "email_header",
    preview: "📧 Email banner format",
    design: {
      name: "Email Header",
      format: "email_header",
      width: 800,
      height: 300,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 800,
          height: 300,
          rotation: 0,
          zIndex: 0,
          backgroundType: "solid",
          backgroundColor: "#4F46E5",
        },
        {
          id: "title",
          type: "text",
          x: 40,
          y: 60,
          width: 720,
          height: 100,
          rotation: 0,
          zIndex: 1,
          text: "Limited Time Offer",
          fontSize: 40,
          fontFamily: "Arial",
          fontColor: "#FFFFFF",
          fontWeight: "900",
          textAlign: "center",
        },
        {
          id: "subtitle",
          type: "text",
          x: 40,
          y: 160,
          width: 720,
          height: 60,
          rotation: 0,
          zIndex: 1,
          text: "Get 50% off today only",
          fontSize: 24,
          fontFamily: "Arial",
          fontColor: "#F3F4F6",
          fontWeight: "normal",
          textAlign: "center",
        },
        {
          id: "cta-button",
          type: "shape",
          x: 300,
          y: 240,
          width: 200,
          height: 50,
          rotation: 0,
          zIndex: 1,
          shapeType: "rectangle",
          fill: "#FBBF24",
        },
        {
          id: "cta-text",
          type: "text",
          x: 300,
          y: 240,
          width: 200,
          height: 50,
          rotation: 0,
          zIndex: 2,
          text: "Shop Now",
          fontSize: 18,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "bold",
          textAlign: "center",
        },
      ],
      backgroundColor: "#4F46E5",
      savedToLibrary: false,
    },
  },

  {
    id: "template-carousel",
    name: "Carousel - Part 1",
    category: "social",
    description: "First slide of a multi-slide carousel post",
    format: "social_square",
    preview: "📑 Carousel slide",
    design: {
      name: "Carousel Slide 1",
      format: "social_square",
      width: 1080,
      height: 1080,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          rotation: 0,
          zIndex: 0,
          backgroundType: "solid",
          backgroundColor: "#FFFFFF",
        },
        {
          id: "slide-number",
          type: "text",
          x: 54,
          y: 54,
          width: 972,
          height: 80,
          rotation: 0,
          zIndex: 1,
          text: "1 of 5",
          fontSize: 32,
          fontFamily: "Arial",
          fontColor: "#6B7280",
          fontWeight: "bold",
          textAlign: "right",
        },
        {
          id: "title",
          type: "text",
          x: 108,
          y: 300,
          width: 864,
          height: 200,
          rotation: 0,
          zIndex: 1,
          text: "Carousel Heading",
          fontSize: 56,
          fontFamily: "Arial",
          fontColor: "#1F2937",
          fontWeight: "900",
          textAlign: "center",
        },
        {
          id: "content",
          type: "text",
          x: 108,
          y: 600,
          width: 864,
          height: 300,
          rotation: 0,
          zIndex: 1,
          text: "Share tips, step-by-step guides, or numbered insights across multiple slides.",
          fontSize: 28,
          fontFamily: "Arial",
          fontColor: "#4B5563",
          fontWeight: "normal",
          textAlign: "center",
        },
        {
          id: "swipe-text",
          type: "text",
          x: 54,
          y: 950,
          width: 972,
          height: 50,
          rotation: 0,
          zIndex: 1,
          text: "← Swipe to continue →",
          fontSize: 18,
          fontFamily: "Arial",
          fontColor: "#9CA3AF",
          fontWeight: "normal",
          textAlign: "center",
        },
      ],
      backgroundColor: "#FFFFFF",
      savedToLibrary: false,
    },
  },

  {
    id: "template-announcement",
    name: "Announcement Banner",
    category: "social",
    description: "Bold announcement with important news",
    format: "social_square",
    preview: "📢 Announcement style",
    design: {
      name: "Announcement Post",
      format: "social_square",
      width: 1080,
      height: 1080,
      items: [
        {
          id: "bg-1",
          type: "background",
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          rotation: 0,
          zIndex: 0,
          backgroundType: "solid",
          backgroundColor: "#DC2626",
        },
        {
          id: "badge",
          type: "shape",
          x: 300,
          y: 150,
          width: 480,
          height: 120,
          rotation: 0,
          zIndex: 1,
          shapeType: "rectangle",
          fill: "#FFFFFF",
        },
        {
          id: "badge-text",
          type: "text",
          x: 300,
          y: 150,
          width: 480,
          height: 120,
          rotation: 0,
          zIndex: 2,
          text: "🎉 NEW & EXCITING",
          fontSize: 32,
          fontFamily: "Arial",
          fontColor: "#DC2626",
          fontWeight: "bold",
          textAlign: "center",
        },
        {
          id: "headline",
          type: "text",
          x: 108,
          y: 350,
          width: 864,
          height: 250,
          rotation: 0,
          zIndex: 1,
          text: "We have something amazing to share!",
          fontSize: 56,
          fontFamily: "Arial",
          fontColor: "#FFFFFF",
          fontWeight: "900",
          textAlign: "center",
        },
        {
          id: "subtext",
          type: "text",
          x: 108,
          y: 650,
          width: 864,
          height: 200,
          rotation: 0,
          zIndex: 1,
          text: "Available starting today",
          fontSize: 32,
          fontFamily: "Arial",
          fontColor: "#FEE2E2",
          fontWeight: "normal",
          textAlign: "center",
        },
      ],
      backgroundColor: "#DC2626",
      savedToLibrary: false,
    },
  },
];

export function getTemplatesByFormat(format: DesignFormat): DesignTemplate[] {
  return DESIGN_TEMPLATES.filter((t) => t.format === format);
}

export function getTemplateById(id: string): DesignTemplate | undefined {
  return DESIGN_TEMPLATES.find((t) => t.id === id);
}
