/**
 * Starter Templates Library
 * 
 * A collection of 18 pre-designed templates for Creative Studio.
 * Templates are brand-adaptive and can be customized with brand colors and fonts.
 */

import type { Design, CanvasItem } from "@/types/creativeStudio";
import type { BrandGuide } from "@/types/brandGuide";

export type TemplateCategory = "quote" | "promo" | "testimonial" | "event" | "carousel" | "cover";
export type TemplateFormat = "square" | "story" | "portrait" | "landscape" | "email" | "flyer";

export interface StarterTemplate {
  id: string;
  name: string;
  category: TemplateCategory;
  format: TemplateFormat;
  description: string;
  previewImageUrl?: string; // For future use with actual preview images
  design: Design; // Full design structure
}

/**
 * Brand adaptation helper
 * Replaces placeholder colors with brand colors from brand kit
 */
function adaptTemplateToBrand(
  items: CanvasItem[],
  brandKit?: BrandGuide | null
): CanvasItem[] {
  if (!brandKit) return items;

  // ✅ FIX: Extract colors from colors array (visualIdentity doesn't have individual color properties)
  const colors = brandKit.visualIdentity?.colors || [];
  // ✅ FIX: Use legacy fields as fallback if available
  const primaryColor = colors[0] || (brandKit as any).primaryColor || "#8B5CF6";
  const secondaryColor = colors[1] || (brandKit as any).secondaryColor || "#F0F7F7";
  const accentColor = colors[2] || (brandKit as any).accentColor || "#EC4899";
  const textPrimary = (brandKit as any).textColor || "#1F2937"; // Default text color
  const textOnPrimary = (brandKit as any).textOnPrimary || "#FFFFFF"; // Default text on primary
  const fontFamily = brandKit.visualIdentity?.typography?.heading || (brandKit as any).fontFamily || "Arial";

  return items.map((item) => {
    const adapted = { ...item };

    // Adapt text colors and fonts
    if (item.type === "text") {
      // Replace placeholder colors with brand colors
      if (item.fontColor === "#8B5CF6" || item.fontColor === "#6366F1") {
        adapted.fontColor = primaryColor;
      } else if (item.fontColor === "#F0F7F7" || item.fontColor === "#F8FAFC") {
        adapted.fontColor = secondaryColor;
      } else if (item.fontColor === "#EC4899" || item.fontColor === "#F97316") {
        adapted.fontColor = accentColor;
      } else if (item.fontColor === "#FFFFFF" && item.backgroundColor === "#8B5CF6") {
        adapted.fontColor = textOnPrimary;
      } else if (!item.fontColor || item.fontColor === "#1F2937") {
        adapted.fontColor = textPrimary;
      }

      // Apply brand font if available
      if (fontFamily && fontFamily !== "Arial") {
        adapted.fontFamily = fontFamily;
      }
    }

    // Adapt shape colors
    if (item.type === "shape") {
      if (item.fill === "#8B5CF6" || item.fill === "#6366F1") {
        adapted.fill = primaryColor;
      } else if (item.fill === "#F0F7F7" || item.fill === "#F8FAFC") {
        adapted.fill = secondaryColor;
      } else if (item.fill === "#EC4899" || item.fill === "#F97316") {
        adapted.fill = accentColor;
      }
    }

    // Adapt background colors
    if (item.type === "background") {
      if (item.backgroundColor === "#8B5CF6" || item.backgroundColor === "#6366F1") {
        adapted.backgroundColor = primaryColor;
      } else if (item.backgroundColor === "#F0F7F7" || item.backgroundColor === "#F8FAFC") {
        adapted.backgroundColor = secondaryColor;
      }

      // Adapt gradient colors
      if (item.backgroundType === "gradient") {
        if (item.gradientFrom === "#8B5CF6" || item.gradientFrom === "#6366F1") {
          adapted.gradientFrom = primaryColor;
        }
        if (item.gradientTo === "#8B5CF6" || item.gradientTo === "#EC4899") {
          adapted.gradientTo = accentColor;
        }
        if (item.gradientFrom === "#F0F7F7") {
          adapted.gradientFrom = secondaryColor;
        }
      }
    }

    return adapted;
  });
}

/**
 * Create a template design with brand adaptation
 */
export function createTemplateDesign(
  template: StarterTemplate,
  brandId: string,
  brandKit?: BrandGuide | null
): Design {
  const adaptedItems = adaptTemplateToBrand(template.design.items, brandKit);
  
  return {
    ...template.design,
    id: `design-${Date.now()}`,
    brandId,
    items: adaptedItems,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// ============================================================================
// TEMPLATE DEFINITIONS
// ============================================================================

/**
 * 1️⃣ SOCIAL POST TEMPLATES (Square 1080×1080)
 */

const SP01_BoldQuoteCard: StarterTemplate = {
  id: "sp-01-bold-quote",
  name: "Bold Quote Card",
  category: "quote",
  format: "square",
  description: "Large centered quote with gradient background",
  design: {
    id: "template-sp-01",
    name: "Bold Quote Card",
    format: "social_square",
    width: 1080,
    height: 1080,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        zIndex: 0,
        backgroundType: "gradient",
        gradientFrom: "#F0F7F7",
        gradientTo: "#8B5CF6",
        gradientAngle: 135,
      },
      {
        id: "quote-text",
        type: "text",
        x: 108,
        y: 350,
        width: 864,
        height: 300,
        rotation: 0,
        zIndex: 2,
        text: '"Your inspirational quote goes here"',
        fontSize: 56,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "brand-bar",
        type: "shape",
        x: 0,
        y: 980,
        width: 1080,
        height: 100,
        rotation: 0,
        zIndex: 1,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
      {
        id: "brand-name",
        type: "text",
        x: 108,
        y: 1000,
        width: 864,
        height: 60,
        rotation: 0,
        zIndex: 2,
        text: "Your Brand Name",
        fontSize: 24,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "normal",
        textAlign: "center",
      },
    ],
    backgroundColor: "#F0F7F7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const SP02_PromoOffer: StarterTemplate = {
  id: "sp-02-promo-offer",
  name: "Promo / New Offer",
  category: "promo",
  format: "square",
  description: "Promotional post with NEW badge and CTA",
  design: {
    id: "template-sp-02",
    name: "Promo Offer",
    format: "social_square",
    width: 1080,
    height: 1080,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#FFFFFF",
      },
      {
        id: "new-badge",
        type: "shape",
        x: 54,
        y: 54,
        width: 200,
        height: 80,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "new-text",
        type: "text",
        x: 104,
        y: 74,
        width: 100,
        height: 40,
        rotation: 0,
        zIndex: 3,
        text: "NEW!",
        fontSize: 32,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "image-placeholder",
        type: "image",
        x: 108,
        y: 200,
        width: 864,
        height: 500,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Product Image",
      },
      {
        id: "headline",
        type: "text",
        x: 108,
        y: 750,
        width: 864,
        height: 120,
        rotation: 0,
        zIndex: 2,
        text: "Special Offer",
        fontSize: 48,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "cta-bar",
        type: "shape",
        x: 0,
        y: 920,
        width: 1080,
        height: 160,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
      {
        id: "cta-text",
        type: "text",
        x: 108,
        y: 960,
        width: 864,
        height: 80,
        rotation: 0,
        zIndex: 3,
        text: "Shop Now",
        fontSize: 36,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#FFFFFF",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const SP03_TestimonialSpotlight: StarterTemplate = {
  id: "sp-03-testimonial",
  name: "Testimonial Spotlight",
  category: "testimonial",
  format: "square",
  description: "Customer testimonial with photo and quote",
  design: {
    id: "template-sp-03",
    name: "Testimonial Spotlight",
    format: "social_square",
    width: 1080,
    height: 1080,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#F0F7F7",
      },
      {
        id: "accent-shape",
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 400,
        rotation: 0,
        zIndex: 1,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
      {
        id: "photo-circle",
        type: "shape",
        x: 390,
        y: 150,
        width: 300,
        height: 300,
        rotation: 0,
        zIndex: 2,
        shapeType: "circle",
        fill: "#FFFFFF",
      },
      {
        id: "quote-text",
        type: "text",
        x: 108,
        y: 500,
        width: 864,
        height: 200,
        rotation: 0,
        zIndex: 2,
        text: '"This product changed my life!"',
        fontSize: 40,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "stars",
        type: "text",
        x: 108,
        y: 720,
        width: 864,
        height: 80,
        rotation: 0,
        zIndex: 2,
        text: "★★★★★",
        fontSize: 48,
        fontFamily: "Arial",
        fontColor: "#FBBF24",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "author-name",
        type: "text",
        x: 108,
        y: 820,
        width: 864,
        height: 60,
        rotation: 0,
        zIndex: 2,
        text: "Sarah Johnson, Happy Customer",
        fontSize: 28,
        fontFamily: "Arial",
        fontColor: "#4B5563",
        fontWeight: "normal",
        textAlign: "center",
      },
    ],
    backgroundColor: "#F0F7F7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

/**
 * 2️⃣ REEL / TIKTOK COVER TEMPLATES (1080×1920 Portrait)
 */

const RT01_CleanTitleCover: StarterTemplate = {
  id: "rt-01-clean-title",
  name: "Clean Title Cover",
  category: "cover",
  format: "portrait",
  description: "Full-bleed background with bold headline",
  design: {
    id: "template-rt-01",
    name: "Clean Title Cover",
    format: "story_portrait",
    width: 1080,
    height: 1920,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        rotation: 0,
        zIndex: 0,
        backgroundType: "gradient",
        gradientFrom: "#8B5CF6",
        gradientTo: "#EC4899",
        gradientAngle: 180,
      },
      {
        id: "image-overlay",
        type: "image",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Background Image",
      },
      {
        id: "headline",
        type: "text",
        x: 108,
        y: 800,
        width: 864,
        height: 300,
        rotation: 0,
        zIndex: 3,
        text: "Your Bold Headline",
        fontSize: 72,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "brand-bar",
        type: "shape",
        x: 0,
        y: 1800,
        width: 1080,
        height: 120,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
      {
        id: "brand-tag",
        type: "text",
        x: 108,
        y: 1820,
        width: 864,
        height: 80,
        rotation: 0,
        zIndex: 3,
        text: "@YourBrand",
        fontSize: 32,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "normal",
        textAlign: "center",
      },
    ],
    backgroundColor: "#8B5CF6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const RT02_SideBarAccent: StarterTemplate = {
  id: "rt-02-side-bar",
  name: "Side Bar Accent",
  category: "cover",
  format: "portrait",
  description: "Vertical color bar with stacked title",
  design: {
    id: "template-rt-02",
    name: "Side Bar Accent",
    format: "story_portrait",
    width: 1080,
    height: 1920,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#FFFFFF",
      },
      {
        id: "main-image",
        type: "image",
        x: 0,
        y: 0,
        width: 720,
        height: 1920,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Main Image",
      },
      {
        id: "color-bar",
        type: "shape",
        x: 720,
        y: 0,
        width: 360,
        height: 1920,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
      {
        id: "title-1",
        type: "text",
        x: 760,
        y: 600,
        width: 280,
        height: 120,
        rotation: 0,
        zIndex: 3,
        text: "YOUR",
        fontSize: 56,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "title-2",
        type: "text",
        x: 760,
        y: 720,
        width: 280,
        height: 120,
        rotation: 0,
        zIndex: 3,
        text: "TITLE",
        fontSize: 56,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#FFFFFF",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const RT03_CreatorIntro: StarterTemplate = {
  id: "rt-03-creator-intro",
  name: "Creator Intro Frame",
  category: "cover",
  format: "portrait",
  description: "Talking head frame with subtitle",
  design: {
    id: "template-rt-03",
    name: "Creator Intro",
    format: "story_portrait",
    width: 1080,
    height: 1920,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#F0F7F7",
      },
      {
        id: "headline",
        type: "text",
        x: 108,
        y: 200,
        width: 864,
        height: 150,
        rotation: 0,
        zIndex: 2,
        text: "Welcome!",
        fontSize: 64,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "photo-placeholder",
        type: "image",
        x: 240,
        y: 500,
        width: 600,
        height: 800,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Talking Head",
      },
      {
        id: "subtitle",
        type: "text",
        x: 108,
        y: 1500,
        width: 864,
        height: 100,
        rotation: 0,
        zIndex: 2,
        text: "Your Subtitle Here",
        fontSize: 40,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "normal",
        textAlign: "center",
      },
      {
        id: "underline",
        type: "shape",
        x: 340,
        y: 1620,
        width: 400,
        height: 4,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
    ],
    backgroundColor: "#F0F7F7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

/**
 * 3️⃣ STORY TEMPLATES (1080×1920)
 */

const ST01_AnnouncementSlide: StarterTemplate = {
  id: "st-01-announcement",
  name: "Announcement Slide",
  category: "event",
  format: "story",
  description: "Large center headline with gradient and CTA",
  design: {
    id: "template-st-01",
    name: "Announcement Slide",
    format: "story_portrait",
    width: 1080,
    height: 1920,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        rotation: 0,
        zIndex: 0,
        backgroundType: "gradient",
        gradientFrom: "#8B5CF6",
        gradientTo: "#F0F7F7",
        gradientAngle: 180,
      },
      {
        id: "headline",
        type: "text",
        x: 108,
        y: 700,
        width: 864,
        height: 400,
        rotation: 0,
        zIndex: 2,
        text: "Big Announcement!",
        fontSize: 80,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "subtext",
        type: "text",
        x: 108,
        y: 1150,
        width: 864,
        height: 150,
        rotation: 0,
        zIndex: 2,
        text: "Something exciting is coming",
        fontSize: 36,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "normal",
        textAlign: "center",
      },
      {
        id: "cta-button",
        type: "shape",
        x: 290,
        y: 1600,
        width: 500,
        height: 120,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "cta-text",
        type: "text",
        x: 340,
        y: 1620,
        width: 400,
        height: 80,
        rotation: 0,
        zIndex: 3,
        text: "Learn More",
        fontSize: 32,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#8B5CF6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const ST02_BeforeAfter: StarterTemplate = {
  id: "st-02-before-after",
  name: "Before / After",
  category: "promo",
  format: "story",
  description: "Two stacked images with labels",
  design: {
    id: "template-st-02",
    name: "Before / After",
    format: "story_portrait",
    width: 1080,
    height: 1920,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#FFFFFF",
      },
      {
        id: "before-image",
        type: "image",
        x: 0,
        y: 0,
        width: 1080,
        height: 900,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Before",
      },
      {
        id: "before-label",
        type: "text",
        x: 54,
        y: 50,
        width: 200,
        height: 80,
        rotation: 0,
        zIndex: 2,
        text: "BEFORE",
        fontSize: 40,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "divider",
        type: "shape",
        x: 0,
        y: 900,
        width: 1080,
        height: 120,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "after-image",
        type: "image",
        x: 0,
        y: 1020,
        width: 1080,
        height: 900,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "After",
      },
      {
        id: "after-label",
        type: "text",
        x: 826,
        y: 1070,
        width: 200,
        height: 80,
        rotation: 0,
        zIndex: 2,
        text: "AFTER",
        fontSize: 40,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#FFFFFF",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const ST03_EventCountdown: StarterTemplate = {
  id: "st-03-countdown",
  name: "Event Countdown",
  category: "event",
  format: "story",
  description: "Countdown timer with event details",
  design: {
    id: "template-st-03",
    name: "Event Countdown",
    format: "story_portrait",
    width: 1080,
    height: 1920,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        rotation: 0,
        zIndex: 0,
        backgroundType: "gradient",
        gradientFrom: "#1F2937",
        gradientTo: "#8B5CF6",
        gradientAngle: 180,
      },
      {
        id: "icon",
        type: "text",
        x: 108,
        y: 300,
        width: 864,
        height: 150,
        rotation: 0,
        zIndex: 2,
        text: "⏰",
        fontSize: 120,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "normal",
        textAlign: "center",
      },
      {
        id: "countdown",
        type: "text",
        x: 108,
        y: 600,
        width: 864,
        height: 300,
        rotation: 0,
        zIndex: 2,
        text: "Event in 7 Days",
        fontSize: 96,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "date-time",
        type: "text",
        x: 108,
        y: 950,
        width: 864,
        height: 200,
        rotation: 0,
        zIndex: 2,
        text: "Date & Time\nLocation",
        fontSize: 40,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "normal",
        textAlign: "center",
      },
      {
        id: "cta-bar",
        type: "shape",
        x: 0,
        y: 1700,
        width: 1080,
        height: 220,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
      {
        id: "cta-text",
        type: "text",
        x: 108,
        y: 1760,
        width: 864,
        height: 100,
        rotation: 0,
        zIndex: 3,
        text: "RSVP Now",
        fontSize: 48,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#1F2937",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

/**
 * 4️⃣ BLOG GRAPHIC TEMPLATES (1200×628 or 1080×1080)
 */

const BG01_BlogCoverLeft: StarterTemplate = {
  id: "bg-01-blog-left",
  name: "Blog Cover with Image Left",
  category: "cover",
  format: "landscape",
  description: "Image left, title right with accent bar",
  design: {
    id: "template-bg-01",
    name: "Blog Cover Left",
    format: "blog_featured",
    width: 1200,
    height: 628,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1200,
        height: 628,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#F0F7F7",
      },
      {
        id: "image-left",
        type: "image",
        x: 0,
        y: 0,
        width: 600,
        height: 628,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Blog Image",
      },
      {
        id: "title",
        type: "text",
        x: 650,
        y: 150,
        width: 500,
        height: 200,
        rotation: 0,
        zIndex: 2,
        text: "Your Blog Title Here",
        fontSize: 48,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "bold",
        textAlign: "left",
      },
      {
        id: "byline",
        type: "text",
        x: 650,
        y: 380,
        width: 500,
        height: 80,
        rotation: 0,
        zIndex: 2,
        text: "By Author Name",
        fontSize: 24,
        fontFamily: "Arial",
        fontColor: "#4B5563",
        fontWeight: "normal",
        textAlign: "left",
      },
      {
        id: "accent-bar",
        type: "shape",
        x: 0,
        y: 580,
        width: 1200,
        height: 48,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
    ],
    backgroundColor: "#F0F7F7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const BG02_FullImageOverlay: StarterTemplate = {
  id: "bg-02-full-overlay",
  name: "Full-Image with Overlay",
  category: "cover",
  format: "landscape",
  description: "Full background image with dark overlay and title",
  design: {
    id: "template-bg-02",
    name: "Full Image Overlay",
    format: "blog_featured",
    width: 1200,
    height: 628,
    brandId: "",
    items: [
      {
        id: "bg-image",
        type: "image",
        x: 0,
        y: 0,
        width: 1200,
        height: 628,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Background",
      },
      {
        id: "overlay",
        type: "shape",
        x: 0,
        y: 0,
        width: 1200,
        height: 628,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
      {
        id: "title",
        type: "text",
        x: 100,
        y: 200,
        width: 1000,
        height: 200,
        rotation: 0,
        zIndex: 3,
        text: "Your Bold Blog Title",
        fontSize: 64,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#8B5CF6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const BG03_QuoteKeyPoint: StarterTemplate = {
  id: "bg-03-quote-point",
  name: "Quote / Key Point Graphic",
  category: "quote",
  format: "square",
  description: "Large text block with accent border",
  design: {
    id: "template-bg-03",
    name: "Quote Key Point",
    format: "social_square",
    width: 1080,
    height: 1080,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#FFFFFF",
      },
      {
        id: "border-top",
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 12,
        rotation: 0,
        zIndex: 1,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "border-left",
        type: "shape",
        x: 0,
        y: 0,
        width: 12,
        height: 1080,
        rotation: 0,
        zIndex: 1,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "border-right",
        type: "shape",
        x: 1068,
        y: 0,
        width: 12,
        height: 1080,
        rotation: 0,
        zIndex: 1,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "border-bottom",
        type: "shape",
        x: 0,
        y: 1068,
        width: 1080,
        height: 12,
        rotation: 0,
        zIndex: 1,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "quote-text",
        type: "text",
        x: 108,
        y: 350,
        width: 864,
        height: 400,
        rotation: 0,
        zIndex: 2,
        text: "Your key point or quote goes here",
        fontSize: 56,
        fontFamily: "Arial",
        fontColor: "#8B5CF6",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "logo",
        type: "text",
        x: 900,
        y: 980,
        width: 150,
        height: 60,
        rotation: 0,
        zIndex: 2,
        text: "Logo",
        fontSize: 20,
        fontFamily: "Arial",
        fontColor: "#4B5563",
        fontWeight: "normal",
        textAlign: "right",
      },
    ],
    backgroundColor: "#FFFFFF",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

/**
 * 5️⃣ EMAIL HEADER TEMPLATES (600×200)
 */

const EH01_MinimalHeader: StarterTemplate = {
  id: "eh-01-minimal",
  name: "Minimal Header",
  category: "cover",
  format: "email",
  description: "Logo left, headline right",
  design: {
    id: "template-eh-01",
    name: "Minimal Header",
    format: "email_header",
    width: 600,
    height: 200,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 600,
        height: 200,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#F0F7F7",
      },
      {
        id: "logo",
        type: "text",
        x: 30,
        y: 70,
        width: 150,
        height: 60,
        rotation: 0,
        zIndex: 2,
        text: "LOGO",
        fontSize: 32,
        fontFamily: "Arial",
        fontColor: "#8B5CF6",
        fontWeight: "bold",
        textAlign: "left",
      },
      {
        id: "headline",
        type: "text",
        x: 200,
        y: 70,
        width: 350,
        height: 60,
        rotation: 0,
        zIndex: 2,
        text: "Your Headline",
        fontSize: 28,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "bold",
        textAlign: "right",
      },
    ],
    backgroundColor: "#F0F7F7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const EH02_CenteredHero: StarterTemplate = {
  id: "eh-02-centered",
  name: "Centered Hero Title",
  category: "cover",
  format: "email",
  description: "Simple centered headline with gradient",
  design: {
    id: "template-eh-02",
    name: "Centered Hero",
    format: "email_header",
    width: 600,
    height: 200,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 600,
        height: 200,
        rotation: 0,
        zIndex: 0,
        backgroundType: "gradient",
        gradientFrom: "#8B5CF6",
        gradientTo: "#EC4899",
        gradientAngle: 90,
      },
      {
        id: "headline",
        type: "text",
        x: 50,
        y: 50,
        width: 500,
        height: 80,
        rotation: 0,
        zIndex: 2,
        text: "Your Hero Title",
        fontSize: 40,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "tagline",
        type: "text",
        x: 50,
        y: 140,
        width: 500,
        height: 40,
        rotation: 0,
        zIndex: 2,
        text: "Your tagline here",
        fontSize: 18,
        fontFamily: "Arial",
        fontColor: "#F0F7F7",
        fontWeight: "normal",
        textAlign: "center",
      },
    ],
    backgroundColor: "#8B5CF6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const EH03_PhotoStrip: StarterTemplate = {
  id: "eh-03-photo-strip",
  name: "Photo Strip Header",
  category: "cover",
  format: "email",
  description: "Photo bar with brand color background",
  design: {
    id: "template-eh-03",
    name: "Photo Strip Header",
    format: "email_header",
    width: 600,
    height: 200,
    brandId: "",
    items: [
      {
        id: "photo-bar",
        type: "image",
        x: 0,
        y: 0,
        width: 600,
        height: 80,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Photo Strip",
      },
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 80,
        width: 600,
        height: 120,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#8B5CF6",
      },
      {
        id: "centered-text",
        type: "text",
        x: 50,
        y: 110,
        width: 500,
        height: 60,
        rotation: 0,
        zIndex: 2,
        text: "Your Brand Message",
        fontSize: 32,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#8B5CF6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

/**
 * 6️⃣ FLYER / POSTER TEMPLATES (1080×1350)
 */

const FL01_EventFlyer: StarterTemplate = {
  id: "fl-01-event-flyer",
  name: "Modern Event Flyer",
  category: "event",
  format: "flyer",
  description: "Event flyer with image, title, and details",
  design: {
    id: "template-fl-01",
    name: "Event Flyer",
    format: "custom",
    width: 1080,
    height: 1350,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#FFFFFF",
      },
      {
        id: "top-image",
        type: "image",
        x: 0,
        y: 0,
        width: 1080,
        height: 600,
        rotation: 0,
        zIndex: 1,
        imageUrl: "placeholder",
        imageName: "Event Image",
      },
      {
        id: "event-title",
        type: "text",
        x: 108,
        y: 650,
        width: 864,
        height: 200,
        rotation: 0,
        zIndex: 2,
        text: "Event Name",
        fontSize: 64,
        fontFamily: "Arial",
        fontColor: "#8B5CF6",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "details",
        type: "text",
        x: 108,
        y: 900,
        width: 864,
        height: 300,
        rotation: 0,
        zIndex: 2,
        text: "📍 Location\n📅 Date & Time\n🎫 Ticket Info",
        fontSize: 32,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "normal",
        textAlign: "center",
      },
    ],
    backgroundColor: "#FFFFFF",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const FL02_CompanyOneSheet: StarterTemplate = {
  id: "fl-02-company-sheet",
  name: "Simple Company One-Sheet",
  category: "promo",
  format: "flyer",
  description: "Header bar with bullet points and CTA",
  design: {
    id: "template-fl-02",
    name: "Company One-Sheet",
    format: "custom",
    width: 1080,
    height: 1350,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        rotation: 0,
        zIndex: 0,
        backgroundType: "solid",
        backgroundColor: "#FFFFFF",
      },
      {
        id: "header-bar",
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 200,
        rotation: 0,
        zIndex: 1,
        shapeType: "rectangle",
        fill: "#8B5CF6",
      },
      {
        id: "header-text",
        type: "text",
        x: 108,
        y: 60,
        width: 864,
        height: 80,
        rotation: 0,
        zIndex: 2,
        text: "Company Name",
        fontSize: 56,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "bullet-1",
        type: "text",
        x: 150,
        y: 300,
        width: 780,
        height: 100,
        rotation: 0,
        zIndex: 2,
        text: "• Key Benefit 1",
        fontSize: 36,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "normal",
        textAlign: "left",
      },
      {
        id: "bullet-2",
        type: "text",
        x: 150,
        y: 420,
        width: 780,
        height: 100,
        rotation: 0,
        zIndex: 2,
        text: "• Key Benefit 2",
        fontSize: 36,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "normal",
        textAlign: "left",
      },
      {
        id: "bullet-3",
        type: "text",
        x: 150,
        y: 540,
        width: 780,
        height: 100,
        rotation: 0,
        zIndex: 2,
        text: "• Key Benefit 3",
        fontSize: 36,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "normal",
        textAlign: "left",
      },
      {
        id: "logo",
        type: "text",
        x: 108,
        y: 1100,
        width: 864,
        height: 100,
        rotation: 0,
        zIndex: 2,
        text: "LOGO",
        fontSize: 48,
        fontFamily: "Arial",
        fontColor: "#4B5563",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "cta-bar",
        type: "shape",
        x: 290,
        y: 1230,
        width: 500,
        height: 80,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "cta-text",
        type: "text",
        x: 340,
        y: 1245,
        width: 400,
        height: 50,
        rotation: 0,
        zIndex: 3,
        text: "Get Started",
        fontSize: 28,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#FFFFFF",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

const FL03_LimitedOffer: StarterTemplate = {
  id: "fl-03-limited-offer",
  name: "Limited-Time Offer Flyer",
  category: "promo",
  format: "flyer",
  description: "Huge percentage/price with subheadline",
  design: {
    id: "template-fl-03",
    name: "Limited Offer",
    format: "custom",
    width: 1080,
    height: 1350,
    brandId: "",
    items: [
      {
        id: "bg-1",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        rotation: 0,
        zIndex: 0,
        backgroundType: "gradient",
        gradientFrom: "#F0F7F7",
        gradientTo: "#FFFFFF",
        gradientAngle: 180,
      },
      {
        id: "big-number",
        type: "text",
        x: 108,
        y: 300,
        width: 864,
        height: 400,
        rotation: 0,
        zIndex: 2,
        text: "50% OFF",
        fontSize: 120,
        fontFamily: "Arial",
        fontColor: "#8B5CF6",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "subheadline",
        type: "text",
        x: 108,
        y: 750,
        width: 864,
        height: 200,
        rotation: 0,
        zIndex: 2,
        text: "Limited Time Only",
        fontSize: 48,
        fontFamily: "Arial",
        fontColor: "#1F2937",
        fontWeight: "bold",
        textAlign: "center",
      },
      {
        id: "footer-bar",
        type: "shape",
        x: 0,
        y: 1250,
        width: 1080,
        height: 100,
        rotation: 0,
        zIndex: 2,
        shapeType: "rectangle",
        fill: "#EC4899",
      },
      {
        id: "footer-text",
        type: "text",
        x: 108,
        y: 1270,
        width: 864,
        height: 60,
        rotation: 0,
        zIndex: 3,
        text: "Shop Now",
        fontSize: 36,
        fontFamily: "Arial",
        fontColor: "#FFFFFF",
        fontWeight: "bold",
        textAlign: "center",
      },
    ],
    backgroundColor: "#F0F7F7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    savedToLibrary: false,
  },
};

// ============================================================================
// EXPORT ALL TEMPLATES
// ============================================================================

export const STARTER_TEMPLATES: StarterTemplate[] = [
  // Social Posts (Square)
  SP01_BoldQuoteCard,
  SP02_PromoOffer,
  SP03_TestimonialSpotlight,
  
  // Reel/TikTok Covers (Portrait)
  RT01_CleanTitleCover,
  RT02_SideBarAccent,
  RT03_CreatorIntro,
  
  // Stories (Portrait)
  ST01_AnnouncementSlide,
  ST02_BeforeAfter,
  ST03_EventCountdown,
  
  // Blog Graphics (Landscape/Square)
  BG01_BlogCoverLeft,
  BG02_FullImageOverlay,
  BG03_QuoteKeyPoint,
  
  // Email Headers (Landscape)
  EH01_MinimalHeader,
  EH02_CenteredHero,
  EH03_PhotoStrip,
  
  // Flyers/Posters (Portrait)
  FL01_EventFlyer,
  FL02_CompanyOneSheet,
  FL03_LimitedOffer,
];

/**
 * Get templates by category
 */
export function getTemplatesByCategory(category: TemplateCategory): StarterTemplate[] {
  return STARTER_TEMPLATES.filter((t) => t.category === category);
}

/**
 * Get templates by format
 */
export function getTemplatesByFormat(format: TemplateFormat): StarterTemplate[] {
  return STARTER_TEMPLATES.filter((t) => t.format === format);
}

